### login
POST http://localhost:4000/login 
Content-Type: application/json 

{   
    "username":"John doe",
    "password": "1234"
}

### POST TWEET
POST http://localhost:5000/tweet
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjM2MjRjZGRiYTMyYjQzOWE5ZGI3OGQiLCJ1c2VybmFtZSI6IkpvaG4gZG9lIiwiaWF0IjoxNjQ3NzE3MDIxLCJleHAiOjE2NDc3MTcwNTF9.C0xRBROjhJWHlt7kfr6kpo8ewCMkKdvzEEcdnIBsjcs
Content-Type: application/json 

{
    "content":"THIS SHOULD BE THE FIRST TWEET"
}
