### REGISTER
POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "User1",
    "password" : "1234"
}
### LOGIN 
POST http://localhost:4000/login
Content-Type : application/json

{
    "username": "User1",
    "password" : "1234"
}
### POST A TWEET
POST http://localhost:5000/tweet
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjYwYTE5Njk1YzJjNmJhNTJlMWRkMTAiLCJ1c2VybmFtZSI6IlVzZXIxIiwiaWF0IjoxNjUxMDk5NTg5LCJleHAiOjE2NTExMDMxODl9.q4lFiDRKDyvL5OLZCzbbs4r3Gd3uEXyjAZ899FV8Kyo
Content-Type: application/json

{
    "content" : "Tweet Content"
}
### LIKE A TWEET
PATCH  http://localhost:5000/tweets/likes/624de6a79ae6993d6df843aa
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjRkZTY0N2EzZTBmMWUwNzVhMjY1OWYiLCJ1c2VybmFtZSI6IlVzZXIxIiwiaWF0IjoxNjUwNDcwOTQ2LCJleHAiOjE2NTA0NzQ1NDZ9.KU2lBwgAbGFgiPq8TYioQHlT0wHrSMDgrivx2nNgd08
###
Get http://localhost:5000/replies/62603045efebedcb896f7a86
### 
Get http://localhost:5000/test/62603045efebedcb896f7a86
### follow user
PATCH http://localhost:4000/users/follow/6260a1a995c2c6ba52e1dd16
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjYwYTE5Njk1YzJjNmJhNTJlMWRkMTAiLCJ1c2VybmFtZSI6IlVzZXIxIiwiaWF0IjoxNjUwNDk5OTk0LCJleHAiOjE2NTA1MDM1OTR9.8HsdHnPUC-9cdiUvPdhaivPkJEfhs6_LSkrzlk8BdpY